name: test_vtpad_reporter
description: Test reporter for vtpdad
version: 0.0.3
homepage: ''

environment:
  sdk: ^3.7.0

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1


dev_dependencies:
  flutter_lints: ^5.0.0
  build: ^2.4.2
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
