name: test_vtpad_reporter
description: Test reporter for vtpdad
version: 0.0.2
homepage:

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dio: ^5.3.3


dev_dependencies:
  flutter_lints: ^2.0.0
  build: ^2.4.1
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
